package migrations

import (
	h "spellslingerer.com/m/v2/migration_helpers"

	"github.com/pocketbase/dbx"
	"github.com/pocketbase/pocketbase/daos"
	m "github.com/pocketbase/pocketbase/migrations"
)

func init() {
	m.Register(func(db dbx.Builder) error {

		decks := []h.Deck{
			{
				Spellslinger: "Ajani",
				Land:         "Savannah",
				Cards: map[string]int{
					"Ajani's Skirmisher":    2,
					"Devoted Steed":         2,
					"Frontline Paladin":     2,
					"Leonin Healer":         2,
					"Horncharge Lantern":    1,
					"Elvish Infuser":        2,
					"Grudge Match":          2,
					"Chapel Geist":          2,
					"Smite the Monstrous":   1,
					"Spiked Baloth":         2,
					"Leonin Kincaller":      2,
					"Ironskin Troll":        2,
					"Ornery Leotau":         2,
					"Strength of the Pride": 2,
					"Briarhorn":             2,
					"Colossal Dreadmaw":     2,
				},
				Code:  "DV1H4sIAAAAAAAAA23KIQ6AMBBEUc9pZqa7zVZiCZKA7P1vgaJBjHv5+fuxndd8bs7C+MgsR6Qh2A0JGiraetUd0RxZhkGtWo7M4SjLJsNUGDLKEPrzBU8llHlXAQAA",
				Image: "/images/cards/tiles/Leonin Kincaller.jpeg",
			},
			{
				Spellslinger: "Drizzt",
				Land:         "Savannah",
				Cards: map[string]int{
					"Shields Up":          2,
					"Elite Vanguard":      2,
					"Gladecover Scout":    2,
					"Devoted Steed":       2,
					"Elvish Archer":       1,
					"Kalonian Tusker":     2,
					"Giant Growth":        2,
					"Grudge Match":        2,
					"Drizzt's Herald":     2,
					"Chapel Geist":        2,
					"Smite the Monstrous": 1,
					"Soul of the Wood":    1,
					"Defend with Twinkle": 2,
					"Hero's Call":         2,
					"Ceremonial Guard":    1,
					"Ironskin Troll":      1,
					"Centaur Archer":      1,
					"Briarhorn":           2,
				},
				Code:  "DV1H4sIAAAAAAAAA23PQQoCMQyF4b13KbxkkqbZuxFciehymE57/ysoylgp2X2LF8hfpbGp16S75STePFViTdpb72SSbcPpel+fD1oL/CByRIIEhHlAgkZk+20LApJKQGCZeL5d3pSJnwGVgEJ8kA3jTEMuE79t4zMexSOIpPzxBdDf4RB5AQAA",
				Image: "/images/cards/tiles/Defend with Twinkle.jpeg",
			},
			{
				Spellslinger: "Kiora",
				Land:         "Tropical Island",
				Cards: map[string]int{
					"Runeshell Crab":     2,
					"Unsummon":           1,
					"Elvish Archer":      2,
					"Kalonian Tusker":    2,
					"Grudge Match":       2,
					"Stardust Moth":      1,
					"Icy Manipulator":    1,
					"Soul of the Wood":   2,
					"Kiora's Tideshaper": 2,
					"Frost Lynx":         2,
					"Shell Game":         1,
					"Sylvan Shrine":      2,
					"Centaur Archer":     2,
					"Drag Under":         2,
					"Shimmering Komodo":  2,
					"Octopummeler":       2,
					"Megapiranha":        2,
				},
				Code:  "DV1H4sIAAAAAAAAA23OOxKAIBAE0dzTzP5gOYKloYUh97+FEUIw2Yu6+jqP+xlvl5Hik0Ayik6KVkIkGGGEkavbYlIrCF2NEOmU7S8UEGL7XQxLQqmFMFwI3WLjB2xcUdxXAQAA",
				Image: "/images/cards/tiles/Octopummeler.jpeg",
			},
			{
				Spellslinger: "Nissa",
				Land:         "Forest",
				Cards: map[string]int{
					"Scion of Ashaya":   2,
					"Rampant Growth":    2,
					"Elvish Archer":     1,
					"Kalonian Tusker":   2,
					"Giant Growth":      1,
					"Grudge Match":      2,
					"Joraga Druid":      2,
					"Soul of the Wood":  1,
					"Spiked Baloth":     2,
					"Sylvan Shrine":     2,
					"Ironskin Troll":    1,
					"Centaur Archer":    2,
					"Ornery Leotau":     2,
					"Bloodlord":         1,
					"Briarhorn":         2,
					"Armored Angel":     1,
					"Mahamoti Djinn":    1,
					"Colossal Dreadmaw": 2,
					"Diving Hellkite":   1,
				},
				Code:  "DV1H4sIAAAAAAAAA23OMQ7AIAxD0b2niRMC4QiVqk5VO3L/W3SCMHh7g/Xl+zyuZ3wvRkiZVFdCuDFqm5QQQvjqihghSifUtsWUUKsQQldBtmdJmBJKr/khCK3lFshuMDp+SCExGFcBAAA=",
				Image: "/images/cards/tiles/Rampant Growth.jpeg",
			},
			{
				Spellslinger: "Gideon",
				Land:         "Plains",
				Cards: map[string]int{
					"Ardent Supporter":     2,
					"Gideon's Protection":  2,
					"Shields Up":           2,
					"Lingering Spirit":     2,
					"Elite Vanguard":       2,
					"Devoted Steed":        2,
					"Frontline Paladin":    2,
					"Sparring Automaton":   1,
					"Gideon's Veteran":     2,
					"Glorious Anthem":      2,
					"Chapel Geist":         2,
					"Smite the Monstrous":  1,
					"Knight Militant":      2,
					"Piston-Fist Pummeler": 2,
					"Rhox Pit Fighter":     2,
					"Armored Angel":        2,
				},
				Code:  "DV1H4sIAAAAAAAAA23Kuw2AMAwG4Z5p/MeOk0yAkCgRlNl/CyoexXWfTrduy37M69TsZg89BayRQMsB9GxAWSAr0JTE+g3BFFEdGCpv9UEsTAN6Kz/eRpX5lFcBAAA=",
				Image: "/images/cards/tiles/Ardent Supporter.jpeg",
			},
			{
				Spellslinger: "Chandra",
				Land:         "Mountain",
				Cards: map[string]int{
					"Shock":                 2,
					"Raging Goblin":         2,
					"Filigree Fox":          2,
					"Regathan Firecat":      2,
					"Goblin Shortcutter":    2,
					"Fire Elemental":        2,
					"Sword Cannoneer":       2,
					"Chandra's Firecrafter": 2,
					"Dragon Hatchling":      2,
					"Blitzing Minotaur":     2,
					"Flame Shot":            2,
					"Axefury Minotaur":      2,
					"Iron Automaton":        2,
					"Kylem Flamewing":       2,
					"Reflective Golem":      2,
				},
				Code:  "DV1H4sIAAAAAAAAA23GIRKAMAxFQc9p8tMkbTUGgWRA9v63QDGDeKt2P7bzWs+tNax9NQ+osBZUVUKtBVTVoD4EVTnUZ4eaCypPqjrUoqA5qdHz1xdwxkyEVwEAAA==",
				Image: "/images/cards/tiles/Fire Elemental.jpeg",
			},
			{
				Spellslinger: "Vivien",
				Land:         "Forest",
				Cards: map[string]int{
					"Lingering Spirit":  1,
					"Gladecover Scout":  2,
					"Beast Bonder":      2,
					"Elvish Archer":     1,
					"Kalonian Tusker":   2,
					"Giant Growth":      1,
					"Grudge Match":      2,
					"Animal Arrow":      2,
					"Courtly Killer":    1,
					"Blitzing Minotaur": 1,
					"Spiked Baloth":     1,
					"Vivien's Arkbow":   2,
					"Sylvan Shrine":     2,
					"Ironskin Troll":    2,
					"Centaur Archer":    1,
					"Ornery Leotau":     1,
					"Briarhorn":         2,
					"Ejected!":          1,
					"Mahamoti Djinn":    1,
					"Megasaurus":        1,
					"Overrun":           1,
				},
				Code:  "DV1H4sIAAAAAAAAA23QuxHAIAwD0D7TSAYbGCF3KXOkZP8tUoEbda+Qv/O+nnd9k6ujbpZom2hD0GoVpGVZhyD9ZIEi6O6CKHZozL6W2RC0gCBtCCJXZ05j7YJgrk7mHyIP8h/4AbDsVwEAAA==",
				Image: "/images/cards/tiles/Animal Arrow.jpeg",
			},
			{
				Spellslinger: "Liliana",
				Land:         "Swamp",
				Cards: map[string]int{
					"Decaying Ghoul":     2,
					"Zombify":            2,
					"Drain Blood":        2,
					"Merchant of Death":  2,
					"Diehard Fan":        2,
					"Famished Fiend":     2,
					"Sparring Automaton": 1,
					"Recycled Grotesque": 2,
					"Rotting Baboon":     2,
					"Gravedigger":        2,
					"Flagrant Foul":      2,
					"Peafoul":            2,
					"Liliana's Goliath":  2,
					"Dark Gladiator":     2,
					"Fearsome Return":    1,
					"Hulking Zombie":     2,
				},
				Code:  "DV1H4sIAAAAAAAAA23KuRGAMAwEwJxqTifJsktgxiEDofvvgognuGyDnfs2j3Wdtjr4MKsJIkuQTkFYKKaiGQWR+TKGoJkJwl2xKEgMRUIQLRT9C9F/vAHweN5VVwEAAA==",
				Image: "/images/cards/tiles/Zombify.jpeg",
			},
			{
				Spellslinger: "Kaya",
				Land:         "Scrubland",
				Cards: map[string]int{
					"Lingering Spirit": 2,
					"Elite Vanguard":   2,
					"Cut Down":         2,
					"Drain Blood":      2,
					"Daggerclaw Imp":   2,
					"Famished Fiend":   2,
					"Ghost Blades":     2,
					"Kaya's Enforcer":  2,
					"Chapel Geist":     2,
					"Courtly Killer":   2,
					"Blood Chalice":    2,
					"Ceremonial Guard": 2,
					"Flagrant Foul":    2,
					"Bloodlord":        2,
					"Armored Angel":    2,
				},
				Code:  "DV1H4sIAAAAAAAAA23NMQ6AIBAF0d7T7F9ggTNoaSRW3P8W2hgspnvFJLPf23HOcWk22ccUFSjLwOIV6MmBYUSJWELAMAOaGnGN/1Qn1ox0Yg9gWsHLBwm3BuVXAQAA",
				Image: "/images/cards/tiles/Ghost Blades.jpeg",
			},
			{
				Spellslinger: "Ral",
				Land:         "Volcanic Island",
				Cards: map[string]int{
					"Spark of Genius":  2,
					"Runeshell Crab":   2,
					"Shock":            2,
					"Unsummon":         2,
					"Arcane Flight":    2,
					"Regathan Firecat": 2,
					"Sword Cannoneer":  2,
					"Divination":       2,
					"Call the Wind":    2,
					"Dragon Hatchling": 2,
					"Magnum Opus":      2,
					"Shell Game":       2,
					"Seismodon":        2,
					"Chaos Lightning":  2,
					"Mahamoti Djinn":   2,
				},
				Code:  "DV1H4sIAAAAAAAAA23QIRKAMAxFQc9p8tM0TSUexTAguf8twDCY51bvvi7bcV+n7pI+9tGAZkX0IMqBoQ5UEr0EDCWwRQP6HMCcDWg1gcoE9hFA+/tePg+AM6hXAQAA",
				Image: "/images/cards/tiles/Chaos Lightning.jpeg",
			},
			{
				Spellslinger: "Nahiri",
				Land:         "Plateau",
				Cards: map[string]int{
					"Shields Up":        2,
					"Lingering Spirit":  2,
					"Shock":             2,
					"Raging Goblin":     2,
					"Frontline Paladin": 2,
					"Sword Cannoneer":   2,
					"Kor Recruit":       2,
					"Nahiri's Outburst": 2,
					"Chapel Geist":      2,
					"Blitzing Minotaur": 2,
					"Willful Smith":     2,
					"Knight Militant":   2,
					"Seismodon":         2,
					"Kylem Flamewing":   2,
					"Armored Angel":     2,
				},
				Code:  "DV1H4sIAAAAAAAAA23GIRKAMAxFQc9p8pMmbSWeQTEge/9boJhBvFV77ttxrefWGoqvVhMa1aHmDSqsqaA+BM0IbEJNg+qCZjSoxYSqCpqTGt1/fQEi9wrAVwEAAA==",
				Image: "/images/cards/tiles/Willful Smith.jpeg",
			},
			{
				Spellslinger: "Angrath",
				Land:         "Badlands",
				Cards: map[string]int{
					"Decaying Ghoul":        2,
					"Shock":                 2,
					"Raging Goblin":         2,
					"Shipwrecker":           2,
					"Searing Chains":        2,
					"Daggerclaw Imp":        2,
					"Famished Fiend":        2,
					"Goblin Vandal":         2,
					"Courtly Killer":        2,
					"Dragon Hatchling":      2,
					"Blitzing Minotaur":     2,
					"Angrath's Deathraider": 2,
					"Flagrant Foul":         2,
					"Axefury Minotaur":      2,
					"Bloodlord":             2,
				},
				Code:  "DV1H4sIAAAAAAAAA23GKxKAMBBEQc9pZjafJRJPoaggc/9boKhCvFZ9XNt5r2d67cqvLTtUUaHGRjXUpUK7AmpTi6gq1BgJVRjaMqDC2gnV6L++MGUQi1cBAAA=",
				Image: "/images/cards/tiles/Angrath's Deathraider.jpeg",
			},
			{
				Spellslinger: "Ashiok",
				Land:         "Underground Sea",
				Cards: map[string]int{
					"Runeshell Crab":      2,
					"Extract Fear":        2,
					"Welkin Tern":         2,
					"Drain Blood":         2,
					"Daggerclaw Imp":      2,
					"Shadowmage Saboteur": 2,
					"Divination":          2,
					"Call the Wind":       2,
					"Courtly Killer":      2,
					"Shell Game":          2,
					"Deathspeaker Naga":   2,
					"Flagrant Foul":       2,
					"Shadowstag":          2,
					"Bloodlord":           2,
					"Mahamoti Djinn":      2,
				},
				Code:  "DV1H4sIAAAAAAAAA23NIRKAMAxFQc9pfhJIU4nHwYDs/W+BYqh4bt3u53Jc47ltlPKjVEArB6oJ6OHAFLIVcLUExhpA/cXM6sgkNgdGbUD1JJpNfAFl4/M7VwEAAA==",
				Image: "/images/cards/tiles/Extract Fear.jpeg",
			},
			{
				Spellslinger: "Serra",
				Land:         "Plains",
				Cards: map[string]int{
					"Shields Up":          1,
					"Lingering Spirit":    2,
					"Elite Vanguard":      2,
					"Serra's Disciple":    2,
					"Devoted Steed":       2,
					"Mend":                1,
					"Frontline Paladin":   1,
					"Elixir of Vitality":  2,
					"Leonin Healer":       1,
					"Sparring Automaton":  1,
					"Glorious Anthem":     1,
					"Serra's Judgment":    2,
					"Chapel Geist":        2,
					"Smite the Monstrous": 2,
					"Ceremonial Guard":    2,
					"Knight Militant":     1,
					"Shrine of Valor":     2,
					"Rhox Pit Fighter":    2,
					"Armored Angel":       1,
				},
				Code:  "DV1H4sIAAAAAAAAA23Quw2AMAyE4Z5pzvErDEBHBwpl9t+CKk5z3Vf88kl+ruN+5zdkdmARcS5qJKHACN2FUOCEphVAogJLRuzW6wJsr4UTQjqhSSNEGqPWH4ISDYSa7QccpmHzVwEAAA==",
				Image: "/images/cards/tiles/Serra's Disciple.jpeg",
			},
			{
				Spellslinger: "Jace",
				Land:         "Island",
				Cards: map[string]int{
					"Runeshell Crab":     2,
					"Remand":             2,
					"Welkin Tern":        2,
					"Unsummon":           2,
					"Sparring Automaton": 2,
					"Divination":         2,
					"Repulse":            2,
					"Call the Wind":      2,
					"Jace's Apprentice":  2,
					"Phantom Monster":    2,
					"Frost Lynx":         2,
					"Mage of Insight":    2,
					"Shell Game":         2,
					"Shimmering Komodo":  2,
					"Mahamoti Djinn":     2,
				},
				Code:  "DV1H4sIAAAAAAAAA23GKxKAMBBEQc9pZshnNxJLIakgc/9boKhCvFZ9Htt1r2d6pfxVSmoWaojqndoatLpDWw9oqQXqCKg0qFmpFjUH1NGhsn99AYLw6PlXAQA",
				Image: "/images/cards/tiles/Remand.jpeg",
			},
			{
				Spellslinger: "Teferi",
				Land:         "Tundra",
				Cards: map[string]int{
					"Shields Up":       2,
					"Elite Vanguard":   2,
					"Disorient":        2,
					"Devoted Steed":    2,
					"Snapshell Turtle": 2,
					"Welkin Tern":      2,
					"Teferi's Staff":   2,
					"Chapel Geist":     2,
					"Call the Wind":    2,
					"Absorb":           2,
					"Teferi's Acolyte": 2,
					"Ceremonial Guard": 2,
					"Frost Lynx":       2,
					"Rhox Pit Fighter": 2,
					"Armored Angel":    2,
				},
				Code:  "DV1H4sIAAAAAAAAA23MIRKAMAwEQM9rLrnQpA/AITtU9v+/QDFUnFu14zruseZjq3B+ROuChhBkQND+bCMZgkgItqQgrAQZFLTukhBEhmJJOgSZvvEFyxOFbVcBAAA=",
				Image: "/images/cards/tiles/Teferi's Acolyte.jpeg",
			},
			{
				Spellslinger: "Domri",
				Land:         "Taiga",
				Cards: map[string]int{
					"Raging Goblin":     2,
					"Gladecover Scout":  2,
					"Kalonian Tusker":   2,
					"Giant Growth":      2,
					"Elvish Infuser":    2,
					"Grudge Match":      1,
					"Forest Patrol":     2,
					"Blitzing Minotaur": 2,
					"Spiked Baloth":     2,
					"Gruul Club":        2,
					"Ironskin Troll":    1,
					"Centaur Archer":    2,
					"Rampaging Boar":    2,
					"Briarhorn":         2,
					"Rampaging Nodorog": 2,
					"Colossal Dreadmaw": 1,
					"Overrun":           1,
				},
				Code:  "DV1H4sIAAAAAAAAA23PIRKAQAxDUc9p0tDS4pHMYBiQe/9boHaKiHvuJ8e1nPd4HxuFmjS6IHJXLAhauCC4KWKdpKcgaIpFwejaj8beyxSMVDQvwQgKgtWH4gMtMCGLVwEAAA==",
				Image: "/images/cards/tiles/Rampaging Boar.jpeg",
			},
			{
				Spellslinger: "Vraska",
				Land:         "Bayou",
				Cards: map[string]int{
					"Decaying Ghoul":     2,
					"Vraska's Throne":    2,
					"Drain Blood":        2,
					"Merchant of Death":  2,
					"Kalonian Tusker":    2,
					"Forest Patrol":      1,
					"Vraska's Grub":      2,
					"Recycled Grotesque": 2,
					"Soul of the Wood":   2,
					"Spiked Baloth":      1,
					"Deathspeaker Naga":  2,
					"Flagrant Foul":      2,
					"Peafoul":            2,
					"Dark Gladiator":     2,
					"Turn to Stone":      2,
					"Megasaurus":         1,
					"Overrun":            1,
				},
				Code:  "DV1H4sIAAAAAAAAA23OuxGAMBAD0ZxqZPl8nx6IGMaE7r8LInCi7GW78zrOez2zrWz8OMIFXZKdgmimmBCkxV+rLggrQQYEkfshXTEoSJQg3ASNFKTtBMYLv0uBcFcBAAA=",
				Image: "/images/cards/tiles/Turn to Stone.jpeg",
			},
			{
				Spellslinger: "Sorin",
				Land:         "Swamp",
				Cards: map[string]int{
					"Bloodline Creator": 2,
					"Filigree Fox":      2,
					"Drain Blood":       2,
					"Daggerclaw Imp":    2,
					"Famished Fiend":    2,
					"Sorin's Feast":     2,
					"Courtly Killer":    2,
					"Blood Chalice":     2,
					"Crafted Glider":    2,
					"Rowdy Reveler":     2,
					"Flagrant Foul":     2,
					"Peafoul":           2,
					"Bloodlord":         2,
					"Dark Gladiator":    2,
					"Reflective Golem":  2,
				},
				Code:  "DV1H4sIAAAAAAAAA23NPQ7CMAwF4J27RLKdh+PcAQmJIhijJm3uf4Sq7UAVvH3D+0FdOy1qodZcA9qswXTtgRs65mYEw+3xLt8PFyPZOT1fhf64BwhwKFEcKnlkHnleYOBx8Ru7krNDjmngORYHHrUkDoWyQ8rqUeEQ6X7hBnz3fRx5AQAA",
				Image: "image",
			},
		}

		dao := daos.New(db)
		for _, deck := range decks {
			err := h.LoadStarterDeck(dao, deck)
			if err != nil {
				return err
			}
		}

		return nil

	}, func(db dbx.Builder) error {
		// add down queries...

		return nil
	})
}
